baseurl = "//portfolio.kellyluo.me"
languageCode = "en-us"
title = "portfolio"
[params]
    author = "kelly luo"
    description = "Hi, I'm Kelly! This is a portfolio of creative projects. I'm a product person and Harvard '20 graduate; an engineer, designer, creator with a love for human stories and experiences."
    sitetitle = "portfolio — kelly luo"